CC = g++
FLAGS = -std=c++11 -pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm
FILES = main.cpp TLongNumber.cpp 
PROG = LAB6
long:
	$(CC) $(FLAGS) -o $(PROG) $(FILES)

clean:
	rm -f *.o long